import { useState, useRef, useEffect } from 'react';
import { usePlaygroundStore } from '../../store/playgroundStore.js';

// ── File download helper ──────────────────────────────────────────────────────

function triggerDownload(filename, content, mimeType = 'application/json') {
  const blob = new Blob([JSON.stringify(content, null, 2)], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ── Postman v2.1 collection builder ──────────────────────────────────────────

function buildPostmanCollection({ apiName, apiDescription, sessionId, endpoints }) {
  const baseUrl = `{{baseUrl}}/api/mock/${sessionId}`;

  const items = endpoints.map((ep) => {
    const hasBody = ['POST', 'PUT', 'PATCH'].includes(ep.method);
    return {
      name: `${ep.method} /${ep.slug}`,
      request: {
        method: ep.method,
        header: [
          { key: 'Content-Type', value: 'application/json', type: 'text' },
          { key: 'x-mockflow-session', value: sessionId, type: 'text' },
        ],
        url: {
          raw:      `${baseUrl}/${ep.slug}`,
          host:     ['{{baseUrl}}'],
          path:     ['api', 'mock', sessionId, ep.slug],
          variable: [],
          query:    [],
        },
        ...(hasBody
          ? {
              body: {
                mode: 'raw',
                raw: JSON.stringify({ example: 'value' }, null, 2),
                options: { raw: { language: 'json' } },
              },
            }
          : {}),
        description: ep.description || '',
      },
      response: [],
    };
  });

  return {
    info: {
      name:        apiName || 'MockFlow AI Collection',
      description: apiDescription || 'Generated by MockFlow AI',
      schema:      'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
      _postman_id: crypto.randomUUID?.() ?? `mf-${Date.now()}`,
    },
    item: [
      {
        name: apiName || 'MockFlow AI',
        item: items,
      },
    ],
    variable: [
      {
        key:   'baseUrl',
        value: 'http://localhost:5000',
        type:  'string',
      },
    ],
    event: [],
  };
}

// ── Schema SDK metadata builder ───────────────────────────────────────────────

function buildSchemaSdk({ apiName, apiDescription, sessionId, endpoints, generatedSchema }) {
  const baseUrl = `http://localhost:5000/api/mock/${sessionId}`;

  return {
    $schema:     'https://mockflow.ai/sdk/v1/schema',
    version:     '1.0.0',
    generatedAt: new Date().toISOString(),
    generatedBy: 'MockFlow AI',
    api: {
      name:        apiName        || 'MockFlow AI',
      description: apiDescription || '',
      sessionId,
      baseUrl,
    },
    schema: generatedSchema ?? {},
    endpoints: endpoints.map((ep) => ({
      slug:         ep.slug,
      method:       ep.method,
      description:  ep.description || '',
      isCollection: ep.isCollection ?? false,
      url:          `${baseUrl}/${ep.slug}`,
      headers: {
        'Content-Type':       'application/json',
        'x-mockflow-session': sessionId,
      },
      example: {
        request:  ['POST', 'PUT', 'PATCH'].includes(ep.method) ? { example: 'value' } : null,
        response: null,  // populated at runtime
      },
    })),
    usage: {
      javascript: `import sdk from './mockflow-sdk.json';\nconst res = await fetch(\`\${sdk.api.baseUrl}/\${sdk.endpoints[0].slug}\`);`,
      curl:       `curl -H "x-mockflow-session: ${sessionId}" ${baseUrl}/${endpoints[0]?.slug ?? 'endpoint'}`,
    },
  };
}

// ── Dropdown menu item ────────────────────────────────────────────────────────

function DropdownItem({ icon, label, sublabel, onClick, flash }) {
  return (
    <button
      className={`flex w-full items-start gap-3 rounded-lg px-3 py-2.5
                  text-left transition-all duration-100
                  hover:bg-gray-800 focus:outline-none focus-visible:ring-1
                  focus-visible:ring-brand-500
                  ${flash ? 'bg-emerald-950/50' : ''}`}
      onClick={onClick}
      role="menuitem"
    >
      <span className="mt-0.5 shrink-0 text-gray-500">{icon}</span>
      <span className="flex flex-col gap-0.5">
        <span className="text-xs font-semibold text-gray-200">{label}</span>
        <span className="text-xs text-gray-600">{sublabel}</span>
      </span>
    </button>
  );
}

// ── ExportDropdown ────────────────────────────────────────────────────────────

export default function ExportDropdown({ compact = false }) {
  const { endpoints, sessionId, apiName, apiDescription, generatedSchema } =
    usePlaygroundStore();

  const [open, setOpen]             = useState(false);
  const [flashItem, setFlashItem]   = useState(null);   // 'postman' | 'sdk'
  const containerRef                = useRef(null);

  // Close on outside click
  useEffect(() => {
    if (!open) return;
    const handler = (e) => {
      if (containerRef.current && !containerRef.current.contains(e.target)) {
        setOpen(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [open]);

  // Close on Escape
  useEffect(() => {
    if (!open) return;
    const handler = (e) => { if (e.key === 'Escape') setOpen(false); };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [open]);

  const flash = (key, fn) => {
    setFlashItem(key);
    fn();
    setTimeout(() => { setFlashItem(null); setOpen(false); }, 600);
  };

  const exportPostman = () => flash('postman', () => {
    const collection = buildPostmanCollection({
      apiName, apiDescription, sessionId, endpoints,
    });
    const slug = (apiName || 'mockflow').toLowerCase().replace(/\s+/g, '-');
    triggerDownload(`${slug}-postman-collection.json`, collection);
  });

  const exportSdk = () => flash('sdk', () => {
    const sdk = buildSchemaSdk({
      apiName, apiDescription, sessionId, endpoints, generatedSchema,
    });
    const slug = (apiName || 'mockflow').toLowerCase().replace(/\s+/g, '-');
    triggerDownload(`${slug}-sdk.json`, sdk);
  });

  const disabled = !endpoints.length;

  return (
    <div className="relative" ref={containerRef}>
      {/* Trigger button */}
      <button
        className={`flex items-center gap-1.5 rounded-lg border px-3 py-1.5
                    text-xs font-semibold transition-all duration-150
                    focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500
                    ${disabled
                      ? 'cursor-not-allowed border-gray-800 bg-gray-900/50 text-gray-700'
                      : open
                        ? 'border-brand-700/60 bg-brand-950/60 text-brand-300 ring-1 ring-brand-700/40'
                        : 'border-gray-700 bg-gray-800/60 text-gray-300 hover:border-gray-600 hover:bg-gray-800 hover:text-gray-100'
                    }`}
        onClick={() => !disabled && setOpen((o) => !o)}
        disabled={disabled}
        aria-haspopup="true"
        aria-expanded={open}
        title={disabled ? 'Generate an API first' : 'Export options'}
      >
        {/* Export icon */}
        <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24"
             stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round"
                d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>

        {!compact && <span>Export</span>}

        {/* Chevron */}
        <svg
          className={`h-3 w-3 transition-transform duration-150
                      ${open ? 'rotate-180' : ''}`}
          fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}
        >
          <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
        </svg>
      </button>

      {/* Dropdown panel */}
      {open && (
        <div
          className="absolute right-0 z-50 mt-2 w-72 animate-fade-in
                     rounded-xl border border-gray-700/80 bg-gray-900
                     shadow-2xl shadow-black/60 ring-1 ring-black/20"
          role="menu"
          aria-label="Export options"
        >
          {/* Panel header */}
          <div className="border-b border-gray-800 px-3 py-2.5">
            <p className="text-xs font-semibold text-gray-400">
              Export Code Bundle
            </p>
            <p className="mt-0.5 text-xs text-gray-700">
              {endpoints.length} endpoint{endpoints.length !== 1 ? 's' : ''} · session{' '}
              <span className="font-mono">{sessionId?.slice(0, 8)}…</span>
            </p>
          </div>

          {/* Actions */}
          <div className="p-1.5" role="none">
            <DropdownItem
              flash={flashItem === 'postman'}
              onClick={exportPostman}
              icon={
                <svg className="h-4 w-4 text-orange-400" fill="none" viewBox="0 0 24 24"
                     stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round"
                        d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
              }
              label="Export Postman Collection"
              sublabel="Postman v2.1 JSON — import directly into Postman or Insomnia"
            />

            <DropdownItem
              flash={flashItem === 'sdk'}
              onClick={exportSdk}
              icon={
                <svg className="h-4 w-4 text-sky-400" fill="none" viewBox="0 0 24 24"
                     stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round"
                        d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                </svg>
              }
              label="Download Local Schema SDK"
              sublabel="JSON metadata config — schema map, endpoint URLs, usage examples"
            />
          </div>

          {/* Footer hint */}
          <div className="border-t border-gray-800 px-3 py-2">
            <p className="text-xs text-gray-700">
              Files are generated client-side · no data leaves your browser
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
